spring.datasource.url=jdbc:postgresql://db-server-hml.sua-empresa.com/tickets_hml
spring.datasource.username=user_hml
spring.datasource.password=${DB_PASSWORD_HML}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate