spring.datasource.url=jdbc:postgresql://db-server-prod.sua-empresa.com/tickets_prod
spring.datasource.username=${DB_USER_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none