spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tickets_dev
spring.datasource.username=${DB_USERNAME_DEV:postgres}
spring.datasource.password=${DB_PASSWORD_DEV:postgres}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=tickets_api
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.format_sql=false
spring.flyway.enabled=true
spring.flyway.schemas=tickets_api
spring.flyway.table-schema=flyway_history
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:default-secret}