spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db-prod-host:5432/tickets_db_prod
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none